import { icon } from '../core/icons.js';

export function renderProjects() {
  return `
    <section class="page-lede-row"><p class="page-lede">Engineering work is more than a finished board. It is the path from constraints to a measured design.</p><span class="note-tag">PORTFOLIO / SELECTED WORK</span></section>
    <section class="featured-project-card"><div class="featured-project-art"><div class="solar-art-label">SPW / 001</div><div class="solar-art-sun">${icon('sun', 34)}</div><div class="solar-art-path"><i></i><i></i><i></i><i></i></div><div class="solar-art-pump">${icon('pump', 48)}</div><div class="solar-art-readout"><span>DEMO NODE</span><strong>18.6 <small>V</small></strong><span>POWER BUS / SIMULATED</span></div></div><div class="featured-project-copy"><p class="eyebrow">FEATURED SYSTEM STUDY / 01</p><h2>Smart solar<br>water pump.</h2><p>A concept for monitoring solar-powered water systems in remote locations. The design connects energy generation, battery storage, controller telemetry and pump health into one operational view.</p><div class="project-tags"><span>EMBEDDED</span><span>ENERGY</span><span>IoT</span><span>FAULT DETECTION</span></div><a class="button button-primary" href="#/solar-pump">Explore system ${icon('arrow', 16)}</a><small class="project-boundary">Prototype study · browser-simulated values · not field hardware</small></div></section>
    <section class="section-block project-list-section"><div class="section-head"><div><p class="eyebrow">ADDITIONAL STUDIES</p><h2>Systems worth exploring.</h2></div><span class="instrument-code">CONCEPTS · NO FABRICATED RESULTS</span></div><div class="project-list"><article class="project-row"><span class="project-index">02</span><div><h3>IoT sensor node</h3><p>ESP32-based concept for sampling, validating and transmitting environmental measurements.</p></div><div class="project-row-tags"><span>ESP32</span><span>MQTT</span></div><span class="project-status">DESIGN CONCEPT</span></article><article class="project-row"><span class="project-index">03</span><div><h3>Embedded communication bench</h3><p>Reference workspace for selecting UART, I²C, SPI and industrial links by system constraints.</p></div><div class="project-row-tags"><span>UART</span><span>CAN</span><span>RS-485</span></div><span class="project-status">REFERENCE LAB</span></article><article class="project-row"><span class="project-index">04</span><div><h3>Energy telemetry dashboard</h3><p>Local demo interface for displaying sensor history, system status and threshold-based alerts.</p></div><div class="project-row-tags"><span>CHARTS</span><span>MONITORING</span></div><span class="project-status">SIMULATION</span></article></div></section>
    <section class="about-card"><div class="about-avatar">SB<span></span></div><div class="about-copy"><p class="eyebrow">ENGINEER / BUILDER</p><h2>Salah Eddine Ben Touati</h2><p>Embedded Systems Engineer focused on connecting electronics, firmware and useful interfaces. This lab is a practical portfolio project—calculations, circuit intuition, embedded references and IoT system thinking in one place.</p><nav class="contact-links" aria-label="Social profiles"><a class="contact-link" href="https://www.linkedin.com/in/salah-eddin-benettouati-98a101310/" target="_blank" rel="noopener noreferrer"><span>LinkedIn</span><span aria-hidden="true">↗</span></a><a class="contact-link" href="https://github.com/salah-eddine-program" target="_blank" rel="noopener noreferrer"><span>GitHub</span><span aria-hidden="true">↗</span></a><a class="contact-link" href="https://salah-eddine-program.github.io/bt-salahdine.com/" target="_blank" rel="noopener noreferrer"><span>Personal website</span><span aria-hidden="true">↗</span></a></nav></div><div class="about-stamp">EMBEDDED<br>ENGINEER<br><span>FIELD NOTES / 2026</span></div></section>
  `;
}
