import { formatNumber } from '../core/format.js';
import { getTelemetry } from '../data/telemetry.js';
import { icon } from '../core/icons.js';

export function renderSolarPump() {
  const sample = getTelemetry();
  return `
    <section class="page-lede-row"><p class="page-lede">A field-system concept for dependable water access, monitored from solar input to pump output.</p><span class="demo-chip"><i class="status-dot"></i> SIMULATION MODE</span></section>
    <section class="solar-hero"><div class="solar-hero-copy"><div class="system-overline"><span>PROJECT / 01</span><span>RENEWABLE SYSTEMS</span><span>EDGE MONITORING</span></div><h2>Smart solar<br><em>water pump.</em></h2><p>A monitoring and control concept for remote water systems. Track energy, water availability and equipment health from one embedded node.</p><div class="pump-status"><span class="pump-status-dot"></span><div><span>PUMP STATUS</span><strong data-pump-status>RUNNING</strong></div><span class="pump-status-meta">NODE / SPW-001</span></div></div><div class="solar-gauge-panel"><div class="gauge-caption"><span>WATER RESERVOIR</span><span>LEVEL SENSOR / DEMO</span></div><div class="water-gauge" data-water-gauge style="--gauge: ${sample.water}%"><div class="water-wave"></div><div class="gauge-value"><strong data-solar="water">${formatNumber(sample.water, 0)}</strong><span>%</span><small>CAPACITY</small></div></div><div class="gauge-foot"><span>LOW THRESHOLD <strong>5%</strong></span><span data-water-condition>NORMAL</span></div></div></section>

    <section class="solar-metric-grid">
      <article class="solar-metric"><span>${icon('sun', 16)} SOLAR VOLTAGE</span><strong><b data-solar="voltage">${formatNumber(sample.voltage, 1)}</b> <small>V</small></strong><div class="metric-microbar"><i style="width:76%"></i></div><small>PV ARRAY · DC BUS</small></article>
      <article class="solar-metric"><span>${icon('waves', 16)} SOLAR CURRENT</span><strong><b data-solar="current">${formatNumber(sample.current, 1)}</b> <small>A</small></strong><div class="metric-microbar"><i style="width:64%"></i></div><small>MPPT OUTPUT · DEMO</small></article>
      <article class="solar-metric"><span>${icon('bolt', 16)} INSTANT POWER</span><strong><b data-solar="power">${formatNumber(sample.power, 1)}</b> <small>W</small></strong><div class="metric-microbar"><i style="width:71%"></i></div><small>V × I · ESTIMATED</small></article>
      <article class="solar-metric"><span>${icon('battery', 16)} BATTERY STATE</span><strong><b data-solar="battery">${formatNumber(sample.battery, 0)}</b> <small>%</small></strong><div class="metric-microbar"><i style="width:${sample.battery}%"></i></div><small>STATE OF CHARGE</small></article>
      <article class="solar-metric"><span>${icon('thermometer', 16)} CONTROLLER TEMP</span><strong><b data-solar="temperature">${formatNumber(sample.temperature, 1)}</b> <small>°C</small></strong><div class="metric-microbar"><i style="width:46%"></i></div><small>LIMIT · 42°C</small></article>
      <article class="solar-metric solar-energy-card"><span>${icon('chart', 16)} ENERGY TODAY</span><strong><b data-solar="energy">${formatNumber(sample.energy, 2)}</b> <small>kWh</small></strong><div class="energy-history-mini"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div><small>LOCAL ESTIMATE · DEMO</small></article>
    </section>

    <section class="solar-lower-grid"><article class="system-panel"><div class="panel-heading"><div><p class="eyebrow">SYSTEM ARCHITECTURE</p><h2>Follow the energy path.</h2></div><span class="instrument-code">POWER → CONTROL → WATER</span></div><div class="system-flow">${[['01', 'sun', 'Solar panel', 'DC generation'], ['02', 'bolt', 'Charge controller', 'MPPT / regulation'], ['03', 'battery', 'Battery', 'Energy storage'], ['04', 'chip', 'Embedded controller', 'Sense + decide'], ['05', 'pump', 'Water pump', 'Actuation']].map(([n, ico, name, detail], index) => `<div class="flow-step"><span class="flow-number">${n}</span><span class="flow-icon">${icon(ico, 20)}</span><strong>${name}</strong><small>${detail}</small>${index < 4 ? `<span class="flow-arrow">${icon('arrow', 15)}</span>` : ''}</div>`).join('')}</div><div class="sensor-list"><span class="eyebrow">SENSED VARIABLES</span><span>WATER LEVEL</span><span>VOLTAGE</span><span>CURRENT</span><span>TEMPERATURE</span></div></article>
      <article class="fault-panel"><div class="panel-heading"><div><p class="eyebrow">FAULT DETECTION</p><h2>System alerts</h2></div><span class="alert-count" data-alert-count>0 ACTIVE</span></div><div class="fault-list" data-fault-list><div class="fault-ok">${icon('check', 18)}<span>No active faults.<small>Thresholds are evaluated on each demo sample.</small></span></div></div><div class="fault-rules"><span>LOW WATER ≤ 5%</span><span>HIGH TEMP &gt; 42°C</span><span>PUMP ON + 0 A</span></div></article></section>

    <section class="scenario-panel"><div><p class="eyebrow">DEMO CONTROLS</p><h2>Exercise the alert logic.</h2><p>Change the simulated sensor state to inspect a fault condition. This does not control real equipment.</p></div><div class="scenario-buttons"><button type="button" class="scenario-button is-selected" data-scenario="normal"><span>01</span>Normal</button><button type="button" class="scenario-button" data-scenario="low-water"><span>02</span>Low water</button><button type="button" class="scenario-button" data-scenario="high-temperature"><span>03</span>High temperature</button><button type="button" class="scenario-button" data-scenario="pump-failure"><span>04</span>Pump failure</button></div></section>
    <div class="data-boundary"><span class="boundary-icon">i</span><div><strong>Prototype boundary</strong><p>Sensor values are simulated in the browser. Motor control, safety interlocks, real sensor calibration and field deployment are not implemented.</p></div><a class="text-link" href="#/documentation">Review the data path ${icon('arrow', 14)}</a></div>
  `;
}
